version: 0.2

phases:
  install:
    commands:
      - echo Installing Node.js dependencies...
      - npm install
  build:
    commands:
      - echo Building the application...
      - npm run build || true
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Preparing to deploy...
artifacts:
  files:
    - '**/*'
    - '!node_modules/**/*'
  base-directory: ./